Btn
ZeinHome/ASAP pull request #7
Opened 2022-01-14 21:16 UTC by axtellion

2022-01-14 23:59 UTC, yanaleso commented on src/sass/components/_button.scss
> +  color: #d41443;
color: $accent-color;

2022-01-14 23:59 UTC, yanaleso commented on src/sass/components/_button.scss
> +  background-color: #ffffff;
background-color: $white-text;

2022-01-14 23:59 UTC, yanaleso commented on src/sass/components/_button.scss
> +    background-color: #ecebeb;
background-color: $hover-btn-bg;

2022-01-15 00:00 UTC, yanaleso commented on src/sass/components/_button.scss
> +    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
box-shadow: 0px 4px 4px $drop-shadow;

2022-01-15 00:00 UTC, yanaleso commented on src/sass/components/_button.scss
> +  background-color: #d41342;
background-color: $accent-color;

2022-01-15 00:01 UTC, yanaleso commented on src/sass/components/_button.scss
> +  color: #ffffff;
color: $white-text;

2022-01-15 00:01 UTC, yanaleso commented on src/sass/components/_button.scss
> +    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
box-shadow: 0px 4px 4px $drop-shadow;

2022-01-15 00:03 UTC, yanaleso commented on src/partials/footer.html
> +  <button class="button button--bg-red">Our Locations</button>
<button type="button" class="button button--bg-red">Our Locations <svg class="contacts__icon" width="10px";
height="10px">
            <use href="../src/images/sprite.svg#icon-arrow"></use>
        </svg> </button>

2022-01-15 00:03 UTC, yanaleso commented on src/partials/footer.html
> +  <button class="button">Our Locations</button>
<button type="button" class="button">Franchise <svg class="contacts__icon" width="10px";
height="10px">
            <use href="../src/images/sprite.svg#icon-arrow"></use>
        </svg> </button>

2022-01-15 00:10 UTC, yanaleso requested changes
в html до кнопок треба додати svg icon-arrow і стилізувати її. В scss кольори поміняти на змінні. І в самому файлі variables змінити $drop-shadow: rgba(0, 0, 0, 0.25);

2022-01-15 00:13 UTC, yanaleso commented on src/partials/footer.html
> +  <button class="button">Our Locations</button>
![image](https://user-images.githubusercontent.com/91130832/149600462-e14d0a9f-34b7-4999-be6d-749c916ee7b6.png)

2022-01-15 09:46 UTC, ZeinHome approved these changes

2022-01-15 10:38 UTC, yanaleso approved these changes

2022-01-15 10:42 UTC, yanaleso commented
варто було би ще додати клас btn-icon і стилізувати зміну кольору свг стрілочки

2022-01-15 12:30 UTC, merged